artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/KartikGarg20526/End-to-End-Customer-Churn-Prediction-using-MLflow-and-DVC/raw/main/data/Churn_Modelling.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
