name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Use v2

      - name: Cache Docker layers
        uses: actions/cache@v3 # Use v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4 # Use v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.render.com/${{ secrets.RENDER_SERVICE_ID }}:latest # Use Service ID for tag

      - name: Deploy to Render
        uses: render-oss/github-action@v1 # Use the dedicated Render action
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}